development:
  server: "http://localhost:9292/faye"
  secret_token: ENV["secret_token"]
test:
  server: "http://localhost:9292/faye"
  secret_token: ENV["secret_token"]
production:
  server: "http://example.com/faye"
  secret_token: ENV["secret_token"]
  signature_expiration: 3600 # one hour
